name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        env:
          ECR_REPOSITORY: 291050483364.dkr.ecr.us-east-1.amazonaws.com/backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REPOSITORY:$IMAGE_TAG \
            ./starter/backend

          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name cluster

      - name: Deploy backend to EKS
        env:
          ECR_REPOSITORY: 291050483364.dkr.ecr.us-east-1.amazonaws.com/backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=$ECR_REPOSITORY:$IMAGE_TAG
          kustomize build | kubectl apply -f -
